// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerCommands.proto

#ifndef PROTOBUF_ServerCommands_2eproto__INCLUDED
#define PROTOBUF_ServerCommands_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_ServerCommands_2eproto();
void protobuf_InitDefaults_ServerCommands_2eproto();
void protobuf_AssignDesc_ServerCommands_2eproto();
void protobuf_ShutdownFile_ServerCommands_2eproto();

class ServerCommand;

// ===================================================================

class ServerCommand : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ServerCommand) */ {
 public:
  ServerCommand();
  virtual ~ServerCommand();

  ServerCommand(const ServerCommand& from);

  inline ServerCommand& operator=(const ServerCommand& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ServerCommand& default_instance();

  static const ServerCommand* internal_default_instance();

  void Swap(ServerCommand* other);

  // implements Message ----------------------------------------------

  inline ServerCommand* New() const { return New(NULL); }

  ServerCommand* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ServerCommand& from);
  void MergeFrom(const ServerCommand& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ServerCommand* other);
  void UnsafeMergeFrom(const ServerCommand& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 command = 1;
  bool has_command() const;
  void clear_command();
  static const int kCommandFieldNumber = 1;
  ::google::protobuf::int32 command() const;
  void set_command(::google::protobuf::int32 value);

  // repeated string content = 2;
  int content_size() const;
  void clear_content();
  static const int kContentFieldNumber = 2;
  const ::std::string& content(int index) const;
  ::std::string* mutable_content(int index);
  void set_content(int index, const ::std::string& value);
  void set_content(int index, const char* value);
  void set_content(int index, const char* value, size_t size);
  ::std::string* add_content();
  void add_content(const ::std::string& value);
  void add_content(const char* value);
  void add_content(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& content() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_content();

  // @@protoc_insertion_point(class_scope:ServerCommand)
 private:
  inline void set_has_command();
  inline void clear_has_command();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::std::string> content_;
  ::google::protobuf::int32 command_;
  friend void  protobuf_InitDefaults_ServerCommands_2eproto_impl();
  friend void  protobuf_AddDesc_ServerCommands_2eproto_impl();
  friend void protobuf_AssignDesc_ServerCommands_2eproto();
  friend void protobuf_ShutdownFile_ServerCommands_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<ServerCommand> ServerCommand_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ServerCommand

// required int32 command = 1;
inline bool ServerCommand::has_command() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ServerCommand::set_has_command() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ServerCommand::clear_has_command() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ServerCommand::clear_command() {
  command_ = 0;
  clear_has_command();
}
inline ::google::protobuf::int32 ServerCommand::command() const {
  // @@protoc_insertion_point(field_get:ServerCommand.command)
  return command_;
}
inline void ServerCommand::set_command(::google::protobuf::int32 value) {
  set_has_command();
  command_ = value;
  // @@protoc_insertion_point(field_set:ServerCommand.command)
}

// repeated string content = 2;
inline int ServerCommand::content_size() const {
  return content_.size();
}
inline void ServerCommand::clear_content() {
  content_.Clear();
}
inline const ::std::string& ServerCommand::content(int index) const {
  // @@protoc_insertion_point(field_get:ServerCommand.content)
  return content_.Get(index);
}
inline ::std::string* ServerCommand::mutable_content(int index) {
  // @@protoc_insertion_point(field_mutable:ServerCommand.content)
  return content_.Mutable(index);
}
inline void ServerCommand::set_content(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:ServerCommand.content)
  content_.Mutable(index)->assign(value);
}
inline void ServerCommand::set_content(int index, const char* value) {
  content_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:ServerCommand.content)
}
inline void ServerCommand::set_content(int index, const char* value, size_t size) {
  content_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ServerCommand.content)
}
inline ::std::string* ServerCommand::add_content() {
  // @@protoc_insertion_point(field_add_mutable:ServerCommand.content)
  return content_.Add();
}
inline void ServerCommand::add_content(const ::std::string& value) {
  content_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:ServerCommand.content)
}
inline void ServerCommand::add_content(const char* value) {
  content_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:ServerCommand.content)
}
inline void ServerCommand::add_content(const char* value, size_t size) {
  content_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:ServerCommand.content)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
ServerCommand::content() const {
  // @@protoc_insertion_point(field_list:ServerCommand.content)
  return content_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
ServerCommand::mutable_content() {
  // @@protoc_insertion_point(field_mutable_list:ServerCommand.content)
  return &content_;
}

inline const ServerCommand* ServerCommand::internal_default_instance() {
  return &ServerCommand_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ServerCommands_2eproto__INCLUDED
